name: CI

on:
  push:
  pull_request:

env:
  CGO_ENABLED: '0' # https://github.com/golang/go/issues/26988
  GO111MODULE: 'on'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Lint Go Code
      uses: docker://golangci/golangci-lint:latest
      with:
        args: golangci-lint run ./... 

  test:
    name: Test (Go ${{ matrix.go }})
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: '1.14'
      - name: Install project dependencies
        run: go get
      - name: Build
        run: go build
      - name: Install test dependencies
        run: composer install --no-progress --no-suggest --ansi
        working-directory: test-push
      - name: Test
        run: go test -v -timeout 30s -coverprofile=cover.out github.com/dunglas/vulcain/gateway
      - name: Upload coverage results
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./cover.out
